# Generated by Django 5.1.3 on 2024-11-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_issues", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptoissue",
            old_name="body",
            new_name="code_snippet",
        ),
        migrations.RenameField(
            model_name="cryptoissue",
            old_name="issue_number",
            new_name="line_number",
        ),
        migrations.RenameField(
            model_name="repository",
            old_name="last_updated",
            new_name="last_analyzed",
        ),
        migrations.RemoveField(
            model_name="cryptoissue",
            name="complexity",
        ),
        migrations.RemoveField(
            model_name="cryptoissue",
            name="html_url",
        ),
        migrations.RemoveField(
            model_name="cryptoissue",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="cryptoissue",
            name="state",
        ),
        migrations.RemoveField(
            model_name="cryptoissue",
            name="title",
        ),
        migrations.RemoveField(
            model_name="cryptoissue",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="cryptoissue",
            name="description",
            field=models.TextField(default="Cryptography issue detected"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptoissue",
            name="file_path",
            field=models.CharField(
                default="Cryptography issue detected", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptoissue",
            name="issue_type",
            field=models.CharField(
                default="Cryptography issue detected", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptoissue",
            name="recommendation",
            field=models.TextField(
                default="Review and update the code following security best practices"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptoissue",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="Review and update the code following security best practices",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repository",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("analyzing", "Analyzing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptoissue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
