# Generated by Django 3.2.25 on 2024-12-01 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_issues', '0002_rename_body_cryptoissue_code_snippet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_analyzed',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='name',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='url',
        ),
        migrations.AddField(
            model_name='repository',
            name='analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_url',
            field=models.URLField(default='https://example.com', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
