# Generated by Django 3.2.25 on 2024-12-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_issues', '0003_auto_20241201_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
    ]
