# Generated by Django 3.2.25 on 2024-12-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_issues', '0004_alter_repository_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoissue',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
